### ISSUE TITLE
position tabs below the content pane?

### ISSUE THREAD

**Issue by vesper8** [spatie/vue-tabs-component#27]
is there a way to allow the tabs to be below the content instead of above?

**Comment by willemvb** [comment]
Currently there's no way to accomplish this in the DOM. You can however try a CSS solution to reverse the order of tabs and content.
In our example CSS, you would also have to tweak the borders of the tabs a bit, since they are 'open' at the bottom right now.

```css
.tabs-component {
    display: flex;
    flex-direction: column-reverse;
    …
}
```
